// Generated By xconfig. DO NOT EDIT!!!

using System.Collections.Generic;
using UnityEngine;

namespace Database
{
    public partial class CfgGM {
        protected CfgGM () {}

        public static CfgGM Instance {
            get {
                return CfgGM.instance;
            }
        }

        public CfgGMData Get(int index) {
            if(this.data == null){
                Debug.LogError($"CONFIG ERROR: CfgGMData CfgGM.Get({index})");
                return default(CfgGMData);
            }
            return this.data.data[index];
        }

        public List<CfgGMData> All() {
            if(this.data == null){
                return default(List<CfgGMData>);
            }
            return this.data.data;
        }
        
        // get CfgGMData object by "idx" with unique
        public CfgGMData GetByIdx(int idx) {

            if(All() == null || All().Count < 1 || !this.ContainsKeyByIdx(idx) )
            {
                Debug.LogError($"CONFIG ERROR: CfgGMData CfgGM.GetByIdx({idx})");
                return default(CfgGMData);
            }
            return this.Get(this.data.index.unique.idx[idx.ToString()]);
        }

        // contains key by "idx" with unique
        public bool ContainsKeyByIdx(int idx) {
            return this.data.index.unique.idx.ContainsKey(idx.ToString());
        }

        public void Parse(string jsonStr) {
            this.data = LitJson.JsonMapper.ToObject<CfgGMRoot>(jsonStr);
        }
        
        protected CfgGMRoot data;
        protected static CfgGM instance = new CfgGM();
    }

    public class CfgGMRoot {
        
        public List<CfgGMData> data { get; set; }

        
        public CfgGMIndexData index { get; set; }
    }

    public class CfgGMData {
        // 命令序号
        
        public int idx { get; set; }
    
        // 命令的名字
        
        public string name { get; set; }
    
        // gm命令的值
        
        public string value { get; set; }
    
        // 参数说明
        
        public string param { get; set; }
    
        public int Idx {
            get {
                return idx;
            }
        }
    
        public string Name {
            get {
                return name;
            }
        }
    
        public string Value {
            get {
                return value;
            }
        }
    
        public string Param {
            get {
                return param;
            }
        }
    }

    public class CfgGMIndexData {
        
        public CfgGMIndexUniqueData unique { get; set; }

        
        public CfgGMIndexMultipleData multiple { get; set; }

        
        public CfgGMIndexComplexData complex { get; set; }
    }

    public class CfgGMIndexUniqueData {

        public Dictionary<string, int> idx { get; set; }
    }

    public class CfgGMIndexMultipleData {}

    public class CfgGMIndexComplexData {}
}
